import {
  FaMobile,
  FaGlobe,
  FaShoppingCart,
  FaCode,
  FaServer,
  FaTools,
  FaSearch,
  FaBell,
  FaPlug,
  FaPaintBrush,
  FaEnvelope,
  FaLaptopCode,
  FaPalette,
  FaRocket,
  FaDatabase,
  FaShieldAlt,
} from "react-icons/fa";

export const servicesData = [
  {
    name: "Лендинги",
    desk: "Одностраничные сайты для продвижения товаров, услуг или мероприятий с высокой конверсией",
    icon: FaRocket,
    price: "от 15 000 руб.",
    technologies: ["HTML/CSS", "JavaScript", "React", "Next.js"],
  },
  {
    name: "Сайты-визитки",
    desk: "Корпоративные сайты для представления компании, портфолио и контактной информации",
    icon: FaGlobe,
    price: "от 20 000 руб.",
    technologies: ["Next.js", "Tailwind CSS", "Framer Motion"],
  },
  {
    name: "Интернет-магазины",
    desk: "Полнофункциональные онлайн-магазины с корзиной, оплатой и системой управления товарами",
    icon: FaShoppingCart,
    price: "от 50 000 руб.",
    technologies: ["Next.js", "Stripe", "MongoDB", "Redux"],
  },
  {
    name: "Верстка по макетам",
    desk: "Точная адаптивная верстка из Figma, Photoshop или Illustrator с сохранением пиксель-перфект",
    icon: FaCode,
    price: "от 10 000 руб.",
    technologies: ["HTML5", "CSS3", "SASS", "JavaScript"],
  },
  {
    name: "Корпоративные сайты",
    desk: "Многостраничные сайты для бизнеса с системой управления контентом и новостями",
    icon: FaLaptopCode,
    price: "от 40 000 руб.",
    technologies: ["Next.js", "Contentful", "TypeScript"],
  },
  {
    name: "Frontend разработка",
    desk: "Создание интерактивных пользовательских интерфейсов на React  или Next.js",
    icon: FaPalette,
    price: "от 30 000 руб.",
    technologies: ["React", "Next.js", "Tailwind"],
  },
  {
    name: "Backend разработка",
    desk: "Разработка серверной части на Node.js, Express, баз данных и API",
    icon: FaServer,
    price: "от 35 000 руб.",
    technologies: ["Node.js", "Express", "PostgreSQL", "REST API"],
  },
  {
    name: "Nest.js разработка",
    desk: "Создание масштабируемых серверных приложений на современном фреймворке Nest.js с TypeScript",
    icon: FaServer,
    price: "от 40 000 руб.",
    technologies: ["Nest.js", "TypeScript", "PostgreSQL", "JWT"],
  },
  {
    name: "Fullstack Nest.js + Next.js",
    desk: "Полный цикл разработки: фронтенд на Next.js и бэкенд на Nest.js - идеальный стек для современных приложений",
    icon: FaLaptopCode,
    price: "от 80 000 руб.",
    technologies: ["Next.js", "Nest.js", "TypeScript", "PostgreSQL", "Redis"],
  },
  {
    name: "REST API на Nest.js",
    desk: "Разработка производительных и безопасных REST API с авторизацией, валидацией и документацией",
    icon: FaPlug,
    price: "от 35 000 руб.",
    technologies: ["Nest.js", "Swagger", "JWT", "Class-validator", "TypeORM"],
  },

  {
    name: "Микросервисы на Nest.js",
    desk: "Разработка микросервисной архитектуры с межсервисным взаимодействием и message brokers",
    icon: FaShieldAlt,
    price: "от 60 000 руб.",
    technologies: ["Nest.js", "RabbitMQ", "Kafka", "gRPC", "Docker"],
  },
  {
    name: "Техническая поддержка",
    desk: "Обслуживание, обновление и доработка существующих сайтов и приложений",
    icon: FaTools,
    price: "от 5 000 руб./мес",
    technologies: ["Технический аудит", "Оптимизация", "Исправление багов"],
  },
  {
    name: "SEO оптимизация",
    desk: "Повышение видимости сайта в поисковых системах и увеличение органического трафика",
    icon: FaSearch,
    price: "от 10 000 руб.",
    technologies: ["Google Analytics", "Semrush", "Meta теги", "Sitemap"],
  },
  {
    name: "PWA приложения",
    desk: "Прогрессивные веб-приложения, которые работают как нативные мобильные приложения",
    icon: FaMobile,
    price: "от 25 000 руб.",
    technologies: ["Next.js PWA", "Service Workers", "Web App Manifest"],
  },
  {
    name: "API интеграции",
    desk: "Интеграция с платежными системами, CRM, мессенджерами и сторонними сервисами",
    icon: FaPlug,
    price: "от 15 000 руб.",
    technologies: ["REST API", "Webhooks", "Payment Gateways"],
  },
  {
    name: "Редизайн сайтов",
    desk: "Современное обновление устаревших сайтов с улучшением UX/UI и функционала",
    icon: FaPaintBrush,
    price: "от 20 000 руб.",
    technologies: ["Figma", "UI/UX дизайн", "Модернизация кода"],
  },
  {
    name: "Верстка email-рассылок",
    desk: "Адаптивная верстка писем, совместимая со всеми почтовыми клиентами",
    icon: FaEnvelope,
    price: "от 8 000 руб.",
    technologies: [
      "HTML для email",
      "Адаптивная верстка",
      "Testing across clients",
    ],
  },
  {
    name: "Next.js приложения",
    desk: "Высокопроизводительные приложения на современном стеке Next.js + TypeScript",
    icon: FaRocket,
    price: "от 45 000 руб.",
    technologies: ["Next.js 14", "TypeScript", "App Router", "Server Actions"],
  },
];
